spring.application.name=ems-backend


# ===============================
# DATABASE
# ===============================

server.port=${PORT:8080}
server.address=0.0.0.0

# In-memory H2 database
spring.datasource.url=jdbc:mysql://localhost:3306/ems

# Database credentials
spring.datasource.username=root
spring.datasource.password=17march1998


# ===============================
# JPA / HIBERNATE
# ===============================


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
## Show SQL queries in the console
#spring.jpa.show-sql=true
#
## Format SQL so it is easier to read
#spring.jpa.properties.hibernate.format_sql=true
#
## Automatically create/update database tables
spring.jpa.hibernate.ddl-auto=update
#
#
## ===============================
## H2 CONSOLE
## ===============================
#
## Enable H2 web console
#spring.h2.console.enabled=true
#
## URL for H2 console
#spring.h2.console.path=/h2-console

# for springboot security
logging.level.org.springframework.security=DEBUG
